name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "DQ11 part 6"
  comment: "Firefox Setup 84.0.2 by torrent-webseed-creator"
  url: "http://s12.bitdl.ir/Dragon%20Quest%20XI%20Echoes%20of%20an%20Elusive%20Age%20%E2%80%93%20Digital%20Edition%20of%20Light[FitGirl%20Repack]/Dragon%20Quest%20XI%20[FitGirl%20Repack].bitdownload.ir.part06.rar"
  file_name: "Dragon%20Quest%20XI%20[FitGirl%20Repack].bitdownload.ir.part06.rar"
  piece_size: 19
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
